// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wazymrsugupnogtcddpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhenltcnN1Z3Vwbm9ndGNkZHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjE3MjMsImV4cCI6MjA3MzI5NzcyM30.lzlNycgsfdLJZhOf9rwet33VS2awmvWj_22TgxUZVhQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);